name: Copy
on: [workflow_dispatch]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN_032026 }}
        src_path: /.
        dst_path: /
        dst_owner: LeanQ
        dst_repo_name: ArabidopsisTEatlas
        dst_branch: gh-pages
        src_branch: gh-pages
        username: cborreda
        email: borreda.carfer@gmail.com
