name: Copy
on: [push, workflow_dispatch]
jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.
        dst_path: /
        dst_owner: carbofer
        dst_repo_name: carbofer.roleandopifias.io
        dst_branch: gh-pages
        src_branch: gh-pages
        username: cborreda
        email: borreda.carfer@gmail.com
